services:
  - docker
env:
  - TERM=dumb
jdk:
  - openjdk8
before_script:
  - git pull --tags
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker-compose -f docker/docker-compose.yml up -d mongo-init greenmail wiremock
script:
  - ./gradlew -Prelease.useLastTag=true final clean check docker dockerTag dockerPush
after_script:
  - docker-compose -f docker/docker-compose.yml down
cache:
  directories:
  - "$HOME/.gradle"