services:
  - docker
env:
  - TERM=dump
script:
  - ./docker/compose run --rm gradle clean check
  - ./docker/compose run --rm gradle shadowJar
cache:
  directories:
  - "$HOME/.gradle"
branches:
  only:
    - master
