services:
  - docker
env:
  - TERM=dump
script:
  - ls -lah "${HOME}/.ssh"
  - ./docker/compose run --rm gradle --stacktrace clean check final docker dockerTag dockerPush
cache:
  directories:
  - "$HOME/.gradle"
branches:
  only:
    - master
