services:
  - docker
env:
  - TERM=dump
script:
  - docker-compose -f docker/docker-compose.yml run --rm gradle --stacktrace clean check docker dockerTag dockerPush
after_script:
  - docker-compose -f docker/docker-compose.yml down
cache:
  directories:
  - "$HOME/.gradle"
branches:
  only:
    - master
