services:
  - docker
env:
  - TERM=dumb
jdk:
  - openjdk8
script:
  - ./gradlew run
cache:
  directories:
  - "$HOME/.gradle"
branches:
  only:
    - master
notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
