services:
  - docker
env:
  - TERM=dumb
jdk:
  - openjdk8
before_script:
  - docker run --rm -d -p "27017:27017" --name=mongo mongo:3.2
  - docker run --rm -d -p "8080:8080" --name wiremock rodolpheche/wiremock
  - docker run --rm -d -p "3025:3025" -p "3143:3143" --name greenmail greenmail/standalone:1.5.7
script:
  - ./gradlew test run
after_script:
  - docker rm -f mongo wiremock greenmail
cache:
  directories:
  - "$HOME/.gradle"
branches:
  only:
    - master
